#
name: Data Clear

on: [push]

jobs:
  run_dataClear:
    runs-on: ubuntu-latest
    steps:

      - name: Check conteudo do repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Instala python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instala os pacotes do requirements (ETL)
        run: |
          python -m pip install --upgrade pip
          pip install -r ETL/requirements_data_for_clear.txt

      - name: Executa Notebook
        run: |
          jupyter execute ETL/data_etl.ipynb
        shell: bash 
          
      - name: commit updated notebook
        uses: EndBug/add-and-commit@v9
        with:
          add: 'AED'
          message: 'AED'

  run_dataAnalysis:
    needs: run_dataClear
    runs-on: ubuntu-latest

    steps:
      - name: Check conteudo do repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Instala python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instala os pacotes do requirements (ANALYSIS)
        run: |
          python -m pip install --upgrade pip
          pip install -r Analysis/requirements_analysis.txt

      - name: Executa Notebook
        run: |
          jupyter execute Analysis/consumidor.ipynb
        shell: bash 
          
      - name: commit updated notebook
        uses: EndBug/add-and-commit@v9
        with:
          add: 'AED'
          message: 'AED'
