name: Security

on: [push]

jobs:
  run_bandit:
    runs-on: ubuntu-latest
    steps:

      - name: Check conteudo do repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Instala python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instala o pacote bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Executa 'bandit'
        run: |
          bandit /*.py -n 3 -lll    